---
com.adobe.acrobat.pro:
  name: Adobe Acrobat
  types:
    - pdf

com.google.chrome:
  name: Google Chrome
  types:
    - browser

com.microsoft.edgemac:
  name: Microsoft Edge
  types:
    - browser

com.microsoft.Outlook:
  name: Microsoft Outlook
  types:
    - calendar
    - mail
