---
browser:
  protocols:
    - http
    - https
  utis:
    - public.url: all
    - public.html: viewer
    - public.xhtml: all

calendar:
  protocols:
    - webcal
  utis:
    - com.apple.ical.ics: all
    - com.apple.ical.vcs: all

mail:
  protocols:
    - mailto

pdf:
  utis:
    - com.adobe.pdf: all
